name: infradata_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - geopandas
  - pyarrow
  - pytest
  - requests
  - python-dotenv
  - camelot-py
  - streamlit>=1.28
  - folium>=0.14
  - streamlit-folium>=0.11
  - pip
  - pip:
    - -e .
