name: Run Tests

on:
  push:
    branches: [ entrega-intermediaria-release ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
        conda-channels: conda-forge
    
    - name: Create conda environment
      shell: bash -l {0}
      run: |
        conda env create -f environment.yml
        conda activate infradata_env
    
    - name: Run tests
      shell: bash -l {0}
      run: |
        micromamba activate infradata_env
        pytest tests/ -v
